name: Release

on:
  workflow_run:
    workflows: ['CI']
    types:
      - completed
    branches: [main]

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HUSKY: 0
        run: npx semantic-release

      - name: Rebuild after version update
        if: success()
        run: npm run build:prod

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: release-build-artifacts
          path: dist/
          retention-days: 7
